# an orchestrator for the containers

services:
  # first, build the nginx server
  nginx_server:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  # secondly, run test runner
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - nginx_server
