FROM ubuntu:latest

# Install Nginx
RUN apt-get update && apt-get install -y nginx

# Copy configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 8080 8081

CMD ["nginx", "-g", "daemon off;"]